### ISSUE TITLE
[BUG] make OPENSEARCH_HOME=/usr/share/opensearch accessible to all

### ISSUE THREAD

**Issue by Andrei-Stepanov** [opensearch-project/docker-images#18]
Hello, please make OPENSEARCH_HOME=/usr/share/opensearch accessible to all

```
podman run -it opensearchproject/opensearch:2.5.0 /bin/bash
[opensearch@e212867ab4f5 ~]$ ls -lnad /usr/share/opensearch
drwx------. 1 1000 1000 20 Feb 21 20:44 /usr/share/opensearch
[opensearch@e212867ab4f5 ~]$ ls -lnad /usr/share
drwxr-xr-x. 1 0 0 24 Feb 21 20:43 /usr/share
[opensearch@e212867ab4f5 ~]$ 
```

```
oc logs opensearch-cluster-master-0
/bin/bash: ./opensearch-docker-entrypoint.sh: Permission denied
```

Just because it doesn't have access to `/usr/share/opensearch` dir

**Comment by peterzhuamazon** [comment]
Hi @WhiteOlivierus we are not using this repo for building docker images.
All the building scripts are currently reside here:
https://github.com/opensearch-project/opensearch-build/tree/main/docker

Thanks.
