### ISSUE TITLE
[BUG] Snake case environment variables for settings do not work

### ISSUE THREAD

**Issue by gowrizrh** [opensearch-project/docker-images#20]
### What is the bug?
We are migrating from Elasticsearch to Opensearch. We mostly use bitbucket pipelines to run functional or integration api testing where Elasticsearch is required as a service.

Currently, configuration of Opensearch via Docker variables is possible. `-e discovery.type=single-node`

However, Bitbucket pipelines does not allow dots in variable definition for services.

See https://jira.atlassian.com/browse/BCLOUD-18007

> As a very quick example, running `echo $DOT.VARIABLE` in Shell or Bash would evaluate `$DOT` as a variable and then append `.VARIABLE` verbatim, rather than evaluate `$DOT.VARIABLE` as a whole. Though there are some scenarios where this does work as expected, such as how Elasticsearch reads the variables.

> As far as I can tell from this ticket, this feature was needed primarily for the Elasticsearch Docker image. And Elasticsearch has offered a workaround for this problem:

See Elasticsearch's workaround https://github.com/elastic/elasticsearch/issues/74036

For example `discovery.type` would become `ES_SETTING_DISCOVERY_TYPE`. This type of environment variable no longer works in Opensearch and it fails to boot up because of the bootstrap checks.

### How can one reproduce the bug?
Start a simple container passing in a snake cased variant of the configuration option.

`docker run --rm -it -e "ES_SETTING_DISCOVERY_TYPE=single-node" opensearchproject/opensearch:latest`

Results in the following logs
```
[2023-03-16T23:39:08,792][INFO ][o.o.b.BootstrapChecks    ] [fcd52ae49431] bound or publishing to a non-loopback address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed
[1]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_cluster_manager_nodes / cluster.initial_master_nodes] must be configured
ERROR: OpenSearch did not exit normally - check the logs at /usr/share/opensearch/logs/docker-cluster.log
```

### What is the expected behavior?
A workaround or an alternative syntax to pass in variables without the dot format like Elasticsearch.

For example the docker environment variable `ES_SETTING_DISCOVERY_TYPE` is the same as `discovery.type`

### What is your host/environment?
Docker version 23.0.1, build a5ee5b1

### Do you have any additional context?
I am not sure if this is the right repository to raise this but it seems to be the most related.

**Comment by adrach** [comment]
any news here?

**Comment by peterzhuamazon** [comment]
Hi we are not using this repo for building docker images.
All the building scripts are currently reside here:
https://github.com/opensearch-project/opensearch-build/tree/main/docker

Thanks.

**Comment by lbajsarowicz** [comment]
I am also facing the issue. Still looking for potential solutions.
