### ISSUE TITLE
[BUG] Change PA log name

### ISSUE THREAD

**Issue by dzane17** [opensearch-project/docker-images#23]
### What is the bug?
PA log has been moved out of `/tmp` dir to `$OPENSEARCH_HOME/logs/PerformanceAnalyzer.log` [PR](https://github.com/opensearch-project/performance-analyzer-rca/pull/315). Please change PA log name [here](https://github.com/opensearch-project/docker-images/blob/main/2.x/bin/opensearch-docker-entrypoint.sh#L61) from `performance-analyzer.log` to `PerformanceAnalyzer.log`.

**Comment by peterzhuamazon** [comment]
We will not change in this repo as it will get all the changes from build in a later phase.

**Comment by peterzhuamazon** [comment]
cc: @rishabh6788 fyi.
