### ISSUE TITLE
[FEATURE] Docker rootless support

### ISSUE THREAD

**Issue by WhiteOlivierus** [opensearch-project/docker-images#30]
### Is your feature request related to a problem?
We are using a docker rootless solution where we would like to host Open Search. But this is not possible because of the memlock attribute. The error that is given is `[1]: memory locking requested for OpenSearch process but memory is not locked` because you can't do a memlock without root.

```yaml
memlock:
  soft: -1
  hard: -1
```

### What solution would you like?
I would like not to have to lock memory if I am running this on its own node.

### What alternatives have you considered?
We have thought about running it without docker, but it makes it a lot simpler if it could be deployed with the rest of our stack without a workaround.

**Comment by peterzhuamazon** [comment]
Hi @WhiteOlivierus we are not using this repo for building docker images.
All the building scripts are currently reside here:
https://github.com/opensearch-project/opensearch-build/tree/main/docker

Thanks.
