### ISSUE TITLE
[FEATURE] Set UID and GID of opensearch user and group to 10000

### ISSUE THREAD

**Issue by nilushancosta** [opensearch-project/docker-images#33]
### Is your feature request related to a problem?
[Checkov](https://www.checkov.io/) recommends that the UID of containers run with 10000 or more - Ref: [Ensure containers run with a high UID to avoid host conflict](https://docs.bridgecrew.io/docs/bc_k8s_37)

### What solution would you like?
Change the UID (and GID to make is consistent) defined in the Dockerfile to 10000

**Comment by peterzhuamazon** [comment]
Hi we are not using this repo for building docker images.
All the building scripts are currently reside here:
https://github.com/opensearch-project/opensearch-build/tree/main/docker

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @nilushancosta ,

I am moving this issue to build repo.
Thanks @nilushancosta for your initial PR here, but I suspect this is a breaking change to add.
Since many users might already turn their script to lock on to 1000 id.

I am happy to continue the discussion in build repo there.

Thanks.
