### ISSUE TITLE
[FEATURE] permission to /usr/share/opensearch

### ISSUE THREAD

**Issue by biernatt** [opensearch-project/docker-images#39]
hello Opensearch team,

I have tried to deploy opensearch via helm chart on RedHat Openshift and at the end its failed because :

`Error: container create failed: time="2024-01-19T19:38:53Z" level=error msg="runc create failed: unable to start container process: exec: \"./opensearch-docker-entrypoint.sh\": stat ./opensearch-docker-entrypoint.sh: permission denied"`

I needed to turn off securityContext nad podSecurityContext parameters from statefulset.yaml because in our OCP setup I dont have permission to use securityContext 

Based on image opensearchproject/opensearch:2.11.1 I notice that you define UID and GID and USER in Docerfile, and thats I think is not the problem at all but the problem for me is the permission of opensearch  /usr/share/opensearch directory 

```
[opensearch@9d45e03aa2fb share]$ ls -la /usr/share/
drwx------.  1 opensearch opensearch   20 Nov 29 22:41 opensearch
```

Quesion that permision 700 is required ?

Im still working to debug this if it a real problem , for that I need to create my on image with fixed dir permission.

**Comment by rishabh6788** [comment]
This repo is not actively maintained, if you want to generate docker image please refer https://github.com/opensearch-project/opensearch-build/tree/main/docker/release.
